# theme: jekyll-theme-cayman
# Exclude files from Jekyll build
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
exclude:
    - README.md
    - LICENSE
    - CNAME
    - Gemfile
    - Gemfile.lock
    - vendor

# Installed gems
plugins:
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji



# Gem settings


# Site Author
author:
  name             : "Evelyn J Boettcher"
  avatar           : "/assets/img/index/evelyn_boettcher_2022_3_4.png"
  bio              : "Physicist and Founder"
  location         : "Dayton"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.didactex.com"
    - label: "GitHub"
      icon: "fas fa-code-branch"
      url: "https://github.com/ejboettcher"
    - label: "Instructables"
      icon: "fas fa-file"
      url: "https://www.instructables.com/member/Gem+City+Sewn/"


# Site settings
encoding: utf-8
locale          : "en-US"
lang            : en-US
title           : "Evelyn J. Boettcher"
title_separator : "-"
subtitle        : "CV"
tesser          : "/assets/img/logos/dayton_gearfilled@128px.png"
logo            : "/assets/img/logos/dayton_gearfilled@128px.png"
description: "Evelyn J. Boettcher CV"
#baseurl: "/evelyn_j_boettcher_cv"
#url: "https://ejboettcher.github.io"
baseurl: ""
url: "http://www.evelyn.boettcher.com"
#repo: "/evelyn_j_boettcher_cv"
repo: ""
repository: "evelyn_j_boettcher_cv/ejboettcher.github.io"
email: "evelyn.boettcher@gmail.com"
header:
  overlay_image: "/assets/img/banner/green_painting.png"
  caption: "Evelyn J. Boettcher"
  image_description: "Green painting banner Image"
#google_analytics: UA-92956541-1
css_inline: false
markdown: kramdown
highlighter: rouge
markdown_ext: ignoreme
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true


# The Reveal theme
reveal_theme: black.css
# The Reveal transition
reveal_transition: default
# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/dist/theme/
# Additional custom CSS paths
extra_css:
# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet:
# Embed Server-side speaker notes?
reveal_notes_server: false
# Additional reveal.js options
reveal_options:
# Additional reveal.js dependencies
reveal_dependencies:
# Reveal.js subdirectory
reveal_path: reveal.js/




# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ejboettcher"



